sonata_admin:
    title: "Administration Bouffon"
    title_logo: sonata/img/logo.png
    security:
        handler: sonata.admin.security.handler.role
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            home:
                label: "Accéder au site"
                items:
                    - { route: app_home, label: Accueil }
                    - { route: app_show, label: Les spectacles}
            contract:
                label: "Gestion des contrats"
                roles: [ 'ROLE_ADMIN' ]
                items:
                    - { route: app_contract_config, label: Configuration globale }
                    - admin.contract

            workflow:
                label: "Gestion des workflows"
                items:
                    - admin.workflow

            artists:
                label: "Les artistes"
                items:
                    - admin.artist

            posts:
                label: "Les posts"
                items:
                    - admin.blogPost
            projects:
                label: "Les projets"
                items:
                    - admin.show
                    - admin.service
            proContact:
                label: "Les contacts pro"
                roles: [ 'ROLE_ADMIN' ]
                items:
                    - admin.proContact
            contents:
                label: "Les contenus"
                items:
                    - admin.page
            offer:
                label: "Les annonces"
                items:
                    - admin.offer
                    - admin.candidature
            media:
                label: "Gestion des média"
                items:
                    - sonata.media.admin.gallery
                    - sonata.media.admin.media

            job:
                label: "Gestion des métiers"
                roles: [ 'ROLE_ADMIN' ]
                items:
                    - admin.job

            user:
                label: "Gestion des utilisateurs"
                roles: [ 'ROLE_ADMIN' ]
                items:
                    - admin.user
    assets:
        extra_stylesheets:
            - sonata/styles/main.css
        extra_javascripts:
            - bundles/fosckeditor/ckeditor.js
